/* poso-seed.js — biblioteca de posologias sugeridas (dados)
   Carregado pelo gerador-documentos.html via <script src>. Só dados, sem lógica.
   Estrutura: { n:"Nome", k:[apelidos/marcas], l:["linha limpa de posologia", ...] }
   Cresce em lotes. Referência — conferir antes de prescrever. */
window.POSO_SEED_RAW = [
  /* Penicilinas */
  {n:"Penicilina G benzatina", k:["Benzetacil","Penicilina benzatina"], l:["1.200.000 UI IM dose única (faringite estreptocócica)","2.400.000 UI IM dose única (sífilis recente)","2.400.000 UI IM 1x/semana por 3 semanas (sífilis tardia/indeterminada)"]},
  {n:"Penicilina G cristalina", k:["Penicilina G potássica","Benzilpenicilina"], l:["18–24 milhões UI/dia IV divididas 4/4h (neurossífilis, 10–14 dias)","2–3 milhões UI IV 4/4h"]},
  {n:"Penicilina G procaína", l:["600.000 UI IM 12/12h"]},
  {n:"Penicilina V", k:["Fenoximetilpenicilina"], l:["500 mg VO 6/6h por 10 dias"]},
  {n:"Amoxicilina", l:["500 mg VO 8/8h por 7–10 dias","875 mg VO 12/12h por 7–10 dias","2 g VO dose única (profilaxia endocardite, 1h antes)"]},
  {n:"Amoxicilina + clavulanato", k:["Amoxicilina clavulanato de potássio","Clavulin"], l:["875 + 125 mg VO 12/12h por 7–10 dias","500 + 125 mg VO 8/8h por 7–10 dias"]},
  {n:"Ampicilina", l:["500 mg – 1 g VO 6/6h","1–2 g IV 4/4h–6/6h","2 g IV 4/4h (meningite/endocardite por enterococo/Listeria)"]},
  {n:"Ampicilina + sulbactam", k:["Ampicilina sulbactam sódico","Unasyn"], l:["1,5–3 g IV 6/6h"]},
  {n:"Piperacilina + tazobactam", k:["Piperacilina tazobactam sódico","Tazocin"], l:["4,5 g IV 6/6h","4,5 g IV 8/8h","3,375 g IV 6/6h"]},
  {n:"Oxacilina", l:["2 g IV 4/4h (S. aureus MSSA grave / endocardite)","1–2 g IV 4/4h–6/6h"]},
  /* Cefalosporinas */
  {n:"Cefazolina", l:["1–2 g IV 8/8h","2 g IV 8/8h (infecção grave)","2 g IV dose única (profilaxia cirúrgica)"]},
  {n:"Cefalexina", l:["500 mg VO 6/6h por 7 dias","500 mg VO 12/12h (ITU não complicada)"]},
  {n:"Cefadroxila", l:["500 mg – 1 g VO 12/12h"]},
  {n:"Cefuroxima", l:["500 mg VO 12/12h por 7–10 dias","750 mg – 1,5 g IV 8/8h"]},
  {n:"Cefaclor", l:["250–500 mg VO 8/8h"]},
  {n:"Cefixima", l:["400 mg VO 1x/dia (ou 200 mg 12/12h)"]},
  {n:"Cefpodoxima", l:["200 mg VO 12/12h"]},
  {n:"Ceftriaxona", l:["1 g IV/IM 1x/dia","2 g IV 1x/dia","2 g IV 12/12h (meningite)","500 mg IM dose única (gonorreia)"]},
  {n:"Cefotaxima", l:["1–2 g IV 8/8h","2 g IV 4/4h–6/6h (meningite)"]},
  {n:"Ceftazidima", l:["1–2 g IV 8/8h","2 g IV 8/8h (Pseudomonas)"]},
  {n:"Cefepima", k:["Cefepime"], l:["1–2 g IV 8/8h–12/12h","2 g IV 8/8h (neutropenia febril / Pseudomonas)"]},
  {n:"Ceftarolina", k:["Ceftaroline"], l:["600 mg IV 12/12h"]},
  {n:"Ceftazidima + avibactam", k:["Ceftazidima avibactam","Avycaz","Zavicefta"], l:["2,5 g IV 8/8h (infusão em 2h) — ajuste renal"]},
  {n:"Ceftolozana + tazobactam", k:["Ceftolozana tazobactam","Zerbaxa"], l:["1,5 g IV 8/8h (cIAI — associar metronidazol; cUTI)","3 g IV 8/8h (pneumonia hospitalar/associada à ventilação)"]},
  /* Carbapenêmicos / Monobactâmico */
  {n:"Meropenem", l:["1 g IV 8/8h","2 g IV 8/8h (meningite / Pseudomonas)"]},
  {n:"Imipenem + cilastatina", k:["Imipenem cilastatina","Tienam"], l:["500 mg IV 6/6h","1 g IV 6/6h–8/8h (infecção grave)"]},
  {n:"Ertapenem", l:["1 g IV/IM 1x/dia"]},
  {n:"Aztreonam", l:["1–2 g IV 8/8h","2 g IV 6/6h–8/8h (Pseudomonas)"]},
  /* Macrolídeos / Lincosamida */
  {n:"Azitromicina", l:["500 mg VO 1x/dia por 3 dias","500 mg VO no 1º dia, depois 250 mg 1x/dia por mais 4 dias","1 g VO dose única (clamídia/cancro mole)"]},
  {n:"Claritromicina", l:["500 mg VO 12/12h por 7–14 dias"]},
  {n:"Eritromicina", l:["500 mg VO 6/6h"]},
  {n:"Clindamicina", l:["300 mg VO 6/6h por 7 dias","600 mg IV 8/8h","600–900 mg IV 8/8h (infecção grave)"]},
  /* Quinolonas */
  {n:"Ciprofloxacino", l:["500 mg VO 12/12h por 7 dias","400 mg IV 12/12h","750 mg VO 12/12h (Pseudomonas / infecção grave)"]},
  {n:"Levofloxacino", l:["750 mg VO/IV 1x/dia por 5–7 dias","500 mg VO/IV 1x/dia"]},
  {n:"Moxifloxacino", l:["400 mg VO/IV 1x/dia"]},
  {n:"Norfloxacino", l:["400 mg VO 12/12h por 3–7 dias (ITU)"]},
  /* Tetraciclinas / Glicilciclina */
  {n:"Doxiciclina", l:["100 mg VO 12/12h por 7–14 dias"]},
  {n:"Minociclina", l:["100 mg VO 12/12h"]},
  {n:"Tigeciclina", k:["Tygacil"], l:["100 mg IV dose de ataque, depois 50 mg IV 12/12h"]},
  /* Aminoglicosídeos */
  {n:"Gentamicina", l:["3–5 mg/kg/dia IV 1x/dia (dose única diária)","1 mg/kg IV 8/8h (sinergismo)"]},
  {n:"Amicacina", l:["15 mg/kg/dia IV 1x/dia"]},
  {n:"Tobramicina", l:["5–7 mg/kg/dia IV 1x/dia"]},
  /* Glicopeptídeos / Lipopeptídeo */
  {n:"Vancomicina", l:["15–20 mg/kg IV 8/8h–12/12h (alvo por AUC; monitorar nível)","125 mg VO 6/6h por 10 dias (C. difficile)"]},
  {n:"Teicoplanina", l:["400 mg IV 12/12h por 3 doses (ataque), depois 400 mg IV 1x/dia"]},
  {n:"Daptomicina", k:["Cubicin"], l:["4 mg/kg IV 1x/dia (pele e partes moles)","6 mg/kg IV 1x/dia (bacteremia / endocardite direita)","8–10 mg/kg IV 1x/dia (salvamento / VRE) — monitorar CPK"]},
  /* Oxazolidinonas */
  {n:"Linezolida", k:["Linezolid","Zyvox"], l:["600 mg VO/IV 12/12h"]},
  {n:"Tedizolida", k:["Tedizolid"], l:["200 mg VO/IV 1x/dia por 6 dias"]},
  /* Polimixinas */
  {n:"Colistina", k:["Colistimetato","Colistimetato sódico"], l:["Ataque 9 milhões UI IV, depois 4,5 milhões UI 12/12h (ou 3 MUI 8/8h) — ajuste renal, com especialista"]},
  {n:"Polimixina B", l:["Ataque 2–2,5 mg/kg IV, depois 1,25–1,5 mg/kg 12/12h (1 mg = 10.000 UI; não ajustar por função renal)"]},
  /* Sulfas / Nitrofuranos / Nitroimidazóis / Fosfomicina / outros */
  {n:"Sulfametoxazol + trimetoprima", k:["Sulfametoxazol trimetoprima","Cotrimoxazol","Bactrim"], l:["800 + 160 mg VO 12/12h por 7–14 dias","15–20 mg/kg/dia (pelo trimetoprima) IV/VO divididos 6/6h–8/8h (PCP)"]},
  {n:"Nitrofurantoína", l:["100 mg VO 6/6h por 5–7 dias"]},
  {n:"Fosfomicina", k:["Fosfomicina trometamol","Monuril"], l:["3 g VO dose única (cistite não complicada)"]},
  {n:"Metronidazol", l:["500 mg VO 8/8h por 7 dias","400 mg VO 12/12h por 7 dias","500 mg IV 8/8h"]},
  {n:"Tinidazol", l:["2 g VO dose única (tricomoníase/giardíase)","500 mg VO 12/12h por 5 dias (vaginose)"]},
  {n:"Secnidazol", l:["2 g VO dose única"]},
  {n:"Rifaximina", l:["550 mg VO 12/12h (encefalopatia hepática)","200 mg VO 8/8h por 3 dias (diarreia do viajante)"]},
  {n:"Cloranfenicol", l:["50 mg/kg/dia IV divididos 6/6h"]},
  /* Antifúngico/antiviral (herança do lote-piloto; ampliaremos em lotes próprios) */
  {n:"Fluconazol", l:["150 mg VO dose única","150 mg VO 1x/dia"]},
  {n:"Aciclovir", l:["400 mg VO 8/8h por 7–10 dias (herpes simples)","800 mg VO 5x/dia por 7 dias (herpes-zóster)"]},
  /* ══ Lote 2: CLÍNICA GERAL (adulto, referência — ajuste por caso/função renal/peso) ══ */
  /* Analgésicos / antitérmicos / AINEs */
  {n:"Paracetamol", k:["Acetaminofeno"], l:["500–1000 mg VO 6/6h (máx 3 g/dia)","750 mg VO 6/6h se necessário"]},
  {n:"Dipirona", k:["Metamizol","Novalgina"], l:["500–1000 mg VO/IV 6/6h","40 gotas VO 6/6h se necessário"]},
  {n:"Ibuprofeno", l:["400–600 mg VO 8/8h por até 5 dias"]},
  {n:"Naproxeno", l:["500 mg VO 12/12h"]},
  {n:"Diclofenaco", l:["50 mg VO 8/8h por até 5 dias","75 mg IM 1–2x/dia"]},
  {n:"Cetoprofeno", l:["100 mg VO/IV 12/12h"]},
  {n:"Nimesulida", l:["100 mg VO 12/12h por até 5 dias"]},
  {n:"Celecoxibe", l:["200 mg VO 1–2x/dia"]},
  {n:"Tramadol", l:["50–100 mg VO/IV 6/6h se necessário (máx 400 mg/dia)"]},
  {n:"Codeína", l:["30 mg VO 6/6h se necessário"]},
  /* Antieméticos / antiespasmódico */
  {n:"Metoclopramida", l:["10 mg VO/IV 8/8h"]},
  {n:"Bromoprida", l:["10 mg VO/IV 8/8h"]},
  {n:"Domperidona", l:["10 mg VO 8/8h antes das refeições"]},
  {n:"Ondansetrona", l:["4–8 mg VO/IV 8/8h"]},
  {n:"Dimenidrinato", l:["50–100 mg VO 6/6h se necessário"]},
  {n:"Escopolamina", k:["Butilbrometo de escopolamina","Buscopan"], l:["10–20 mg VO/IV 6/6h–8/8h (antiespasmódico)"]},
  /* Inibidores de bomba / antissecretores */
  {n:"Omeprazol", l:["20–40 mg VO 1x/dia em jejum"]},
  {n:"Pantoprazol", l:["40 mg VO/IV 1x/dia"]},
  {n:"Esomeprazol", l:["40 mg VO 1x/dia"]},
  {n:"Lansoprazol", l:["30 mg VO 1x/dia"]},
  {n:"Famotidina", l:["20–40 mg VO 12/12h"]},
  /* Laxantes / antidiarreicos */
  {n:"Loperamida", l:["4 mg VO inicial, depois 2 mg após cada evacuação (máx 16 mg/dia)"]},
  {n:"Lactulose", l:["15–30 mL VO 1–2x/dia"]},
  {n:"Racecadotrila", l:["100 mg VO 8/8h"]},
  /* Anti-histamínicos */
  {n:"Loratadina", l:["10 mg VO 1x/dia"]},
  {n:"Desloratadina", l:["5 mg VO 1x/dia"]},
  {n:"Cetirizina", l:["10 mg VO 1x/dia"]},
  {n:"Fexofenadina", l:["180 mg VO 1x/dia"]},
  {n:"Difenidramina", l:["25–50 mg VO 6/6h–8/8h"]},
  {n:"Hidroxizina", l:["25 mg VO 6/6h–8/8h"]},
  /* Corticoides */
  {n:"Prednisona", l:["20–60 mg VO 1x/dia pela manhã"]},
  {n:"Prednisolona", l:["20–40 mg VO 1x/dia"]},
  {n:"Dexametasona", l:["4 mg VO/IV 1x/dia (ajustar por indicação)","6 mg VO/IV 1x/dia por 10 dias (COVID-19)"]},
  {n:"Betametasona", l:["0,5–4 mg/dia VO/IM"]},
  {n:"Hidrocortisona", l:["100 mg IV 8/8h (dose de estresse)"]},
  /* Cardiovascular — anti-hipertensivos / IC */
  {n:"Losartana", l:["50 mg VO 1x/dia (até 100 mg/dia)"]},
  {n:"Valsartana", l:["80–160 mg VO 1x/dia"]},
  {n:"Enalapril", l:["5–20 mg VO 12/12h"]},
  {n:"Captopril", l:["25 mg VO 8/8h"]},
  {n:"Ramipril", l:["2,5–10 mg VO 1x/dia"]},
  {n:"Anlodipino", k:["Amlodipino"], l:["5–10 mg VO 1x/dia"]},
  {n:"Nifedipino", k:["Nifedipino retard"], l:["20–30 mg VO 12/12h"]},
  {n:"Hidroclorotiazida", l:["25 mg VO 1x/dia"]},
  {n:"Clortalidona", l:["12,5–25 mg VO 1x/dia"]},
  {n:"Indapamida", l:["1,5 mg VO 1x/dia"]},
  {n:"Furosemida", l:["20–40 mg VO/IV 1–2x/dia"]},
  {n:"Espironolactona", l:["25–50 mg VO 1x/dia"]},
  {n:"Atenolol", l:["25–100 mg VO 1x/dia"]},
  {n:"Metoprolol", k:["Succinato de metoprolol"], l:["25–100 mg VO 1x/dia (succinato)"]},
  {n:"Propranolol", l:["40 mg VO 12/12h"]},
  {n:"Carvedilol", l:["3,125–25 mg VO 12/12h"]},
  {n:"Bisoprolol", l:["2,5–10 mg VO 1x/dia"]},
  {n:"Hidralazina", l:["25–50 mg VO 6/6h"]},
  /* Dislipidemia */
  {n:"Sinvastatina", l:["20–40 mg VO 1x/dia à noite"]},
  {n:"Atorvastatina", l:["10–80 mg VO 1x/dia"]},
  {n:"Rosuvastatina", l:["10–40 mg VO 1x/dia"]},
  {n:"Ezetimiba", l:["10 mg VO 1x/dia"]},
  {n:"Fenofibrato", l:["160–200 mg VO 1x/dia"]},
  /* Antiplaquetários / anticoagulantes */
  {n:"Ácido acetilsalicílico", k:["AAS","Aspirina"], l:["100 mg VO 1x/dia (antiagregação)"]},
  {n:"Clopidogrel", l:["75 mg VO 1x/dia (ataque 300–600 mg)"]},
  {n:"Varfarina", k:["Warfarina"], l:["dose individualizada pelo INR (alvo 2–3)"]},
  {n:"Rivaroxabana", k:["Rivaroxaban","Xarelto"], l:["20 mg VO 1x/dia com alimento (FA; 15 mg se ClCr 15–50)","15 mg VO 12/12h por 21 dias, depois 20 mg 1x/dia (TEV)"]},
  {n:"Apixabana", k:["Apixaban","Eliquis"], l:["5 mg VO 12/12h (FA; 2,5 mg se ≥2 de: idade ≥80, peso ≤60 kg, creatinina ≥1,5)","10 mg VO 12/12h por 7 dias, depois 5 mg 12/12h (TEV)"]},
  {n:"Dabigatrana", k:["Dabigatran","Pradaxa"], l:["150 mg VO 12/12h (FA; 110 mg 12/12h em idosos/risco)"]},
  {n:"Edoxabana", k:["Edoxaban"], l:["60 mg VO 1x/dia (FA; evitar se ClCr ≥95; 30 mg se ClCr 15–50)"]},
  {n:"Enoxaparina", k:["Clexane"], l:["1 mg/kg SC 12/12h (terapêutica)","40 mg SC 1x/dia (profilaxia)"]},
  /* Antidiabéticos */
  {n:"Metformina", l:["500–850 mg VO 2–3x/dia com refeições","XR 500–2000 mg VO 1x/dia"]},
  {n:"Glibenclamida", l:["5 mg VO 1x/dia (café da manhã)"]},
  {n:"Gliclazida", k:["Gliclazida MR"], l:["30–120 mg VO 1x/dia (MR)"]},
  {n:"Sitagliptina", l:["100 mg VO 1x/dia"]},
  {n:"Dapagliflozina", k:["Forxiga"], l:["10 mg VO 1x/dia"]},
  {n:"Empagliflozina", k:["Jardiance"], l:["10 mg VO 1x/dia (até 25 mg)"]},
  {n:"Semaglutida oral", k:["Rybelsus"], l:["3 mg VO 1x/dia por 30 dias, depois 7 mg (máx 14 mg); jejum, 30 min antes"]},
  {n:"Semaglutida", k:["Ozempic","Semaglutida injetável"], l:["0,25 mg SC 1x/semana por 4 sem, depois 0,5 mg (até 1–2 mg)"]},
  {n:"Dulaglutida", k:["Trulicity"], l:["0,75 mg SC 1x/semana (até 1,5 mg)"]},
  {n:"Liraglutida", k:["Victoza"], l:["0,6 mg SC 1x/dia por 1 sem, depois 1,2 mg (até 1,8 mg)"]},
  {n:"Insulina NPH", l:["dose individualizada (ex.: iniciar 0,1–0,2 UI/kg/dia; titular pela glicemia)"]},
  {n:"Insulina glargina", l:["dose individualizada 1x/dia (titular pela glicemia de jejum)"]},
  /* Tireoide */
  {n:"Levotiroxina", l:["1,6 mcg/kg/dia VO 1x/dia em jejum (ajustar pelo TSH)","iniciar 25–50 mcg/dia em idoso/cardiopata"]},
  /* Respiratório */
  {n:"Salbutamol", k:["Albuterol"], l:["100–200 mcg (1–2 jatos) inalados 4/4h–6/6h se necessário"]},
  {n:"Budesonida", l:["200–400 mcg inalados 12/12h"]},
  {n:"Budesonida + formoterol", k:["Budesonida formoterol","Symbicort"], l:["1–2 inalações 12/12h"]},
  /* Psicotrópicos — ISRS / ansiolíticos / hipnóticos (vários são controlados) */
  {n:"Sertralina", l:["50 mg VO 1x/dia (até 200 mg)"]},
  {n:"Escitalopram", l:["10 mg VO 1x/dia (até 20 mg)"]},
  {n:"Fluoxetina", l:["20 mg VO 1x/dia (até 60 mg)"]},
  {n:"Paroxetina", l:["20 mg VO 1x/dia"]},
  {n:"Venlafaxina", l:["75 mg VO 1x/dia (até 225 mg)"]},
  {n:"Amitriptilina", l:["25 mg VO à noite (dor/profilaxia; titular até 75 mg)"]},
  {n:"Clonazepam", l:["0,5–2 mg VO à noite (controlado)"]},
  {n:"Diazepam", l:["5–10 mg VO (controlado)"]},
  {n:"Alprazolam", l:["0,25–0,5 mg VO 8/8h (controlado)"]},
  {n:"Zolpidem", l:["10 mg VO à noite (controlado)"]},
  {n:"Quetiapina", l:["25 mg VO 12/12h, titular conforme indicação"]},
  /* ══ Lote 3: ISRS/NEURO, SINTOMÁTICOS, ANTI-HISTAMÍNICOS, GASTRO, TÓPICOS ══ */
  /* Antidepressivos / neuro (adicionais) */
  {n:"Citalopram", l:["20 mg VO 1x/dia (idoso máx 20; adulto máx 40)"]},
  {n:"Duloxetina", k:["Cymbalta"], l:["30–60 mg VO 1x/dia"]},
  {n:"Bupropiona", k:["Wellbutrin"], l:["150 mg VO 1x/dia (XL/SR), até 300 mg/dia"]},
  {n:"Mirtazapina", l:["15–45 mg VO à noite"]},
  {n:"Trazodona", l:["50–100 mg VO à noite (até 300 mg/dia)"]},
  {n:"Nortriptilina", l:["25 mg VO à noite (titular 25–75 mg)"]},
  {n:"Pregabalina", k:["Lyrica"], l:["75 mg VO 12/12h (dor neuropática; até 300 mg/dia)"]},
  {n:"Gabapentina", l:["300 mg VO 8/8h, titular (até 3600 mg/dia)"]},
  /* Sintomáticos: tosse / mucolítico / vertigem / antiflatulento */
  {n:"Acetilcisteína", k:["N-acetilcisteína"], l:["600 mg VO 1x/dia (mucolítico)"]},
  {n:"Ambroxol", l:["30 mg VO 8/8h"]},
  {n:"Dropropizina", l:["30 mg (10 mL) VO 6/6h–8/8h (antitússico)"]},
  {n:"Betaistina", l:["24 mg VO 12/12h (vertigem)"]},
  {n:"Cinarizina", l:["75 mg VO 1x/dia"]},
  {n:"Simeticona", k:["Dimeticona"], l:["40–125 mg VO após as refeições e ao deitar"]},
  /* Anti-histamínicos (adicionais) */
  {n:"Levocetirizina", l:["5 mg VO 1x/dia"]},
  {n:"Ebastina", l:["10 mg VO 1x/dia"]},
  {n:"Bilastina", l:["20 mg VO 1x/dia"]},
  {n:"Rupatadina", l:["10 mg VO 1x/dia"]},
  {n:"Prometazina", l:["25 mg VO/IM à noite ou 8/8h"]},
  {n:"Dexclorfeniramina", l:["2 mg VO 6/6h–8/8h"]},
  /* Gastro (adicionais) */
  {n:"Sucralfato", l:["1 g VO 6/6h, 1h antes das refeições e ao deitar"]},
  {n:"Hidróxido de alumínio + magnésio", k:["Hidróxido de alumínio","Antiácido"], l:["10–15 mL VO após as refeições e ao deitar"]},
  {n:"Mesalazina", k:["Mesalamina"], l:["800 mg – 1,6 g VO 8/8h (DII; manutenção 1,2–2,4 g/dia)"]},
  {n:"Trimebutina", l:["200 mg VO 8/8h"]},
  {n:"Ácido ursodesoxicólico", k:["Ursodiol"], l:["10–15 mg/kg/dia VO divididos 1–2x"]},
  {n:"Polietilenoglicol", k:["PEG","Macrogol"], l:["17 g VO 1x/dia (laxante osmótico)"]},
  {n:"Bisacodil", l:["5–10 mg VO à noite"]},
  /* Tópicos — dermatológicos */
  {n:"Hidrocortisona creme", l:["aplicar fina camada 1–2x/dia (baixa potência)"]},
  {n:"Betametasona creme", l:["aplicar 1–2x/dia na área afetada"]},
  {n:"Mometasona creme", l:["aplicar 1x/dia"]},
  {n:"Clobetasol creme", l:["aplicar 1–2x/dia por até 2 semanas (alta potência)"]},
  {n:"Cetoconazol creme", l:["aplicar 1–2x/dia por 2–4 semanas"]},
  {n:"Cetoconazol xampu", k:["Nizoral"], l:["aplicar 2x/semana, deixar agir 3–5 min"]},
  {n:"Miconazol creme", l:["aplicar 2x/dia"]},
  {n:"Clotrimazol creme", l:["aplicar 2–3x/dia"]},
  {n:"Terbinafina creme", l:["aplicar 1–2x/dia por 1–2 semanas"]},
  {n:"Nistatina", l:["suspensão oral 100.000 UI/mL: 5 mL bochechar e engolir 6/6h (candidíase oral)","creme: aplicar 2–3x/dia (candidíase cutânea)"]},
  {n:"Mupirocina pomada", k:["Bactroban"], l:["aplicar 3x/dia por 5–10 dias"]},
  {n:"Ácido fusídico creme", l:["aplicar 3x/dia"]},
  {n:"Peróxido de benzoíla", l:["aplicar 1x/dia à noite na área acneica"]},
  {n:"Adapaleno", l:["aplicar à noite, fina camada"]},
  {n:"Clindamicina gel", l:["aplicar 2x/dia (acne)"]},
  {n:"Tretinoína", l:["aplicar à noite (iniciar em dias alternados)"]},
  {n:"Permetrina", l:["loção 5%: aplicar do pescoço para baixo, deixar 8–14h; repetir em 7 dias (escabiose)"]},
  /* Tópicos — oftálmicos */
  {n:"Tobramicina colírio", l:["1 gota 4/4h–6/6h"]},
  {n:"Ciprofloxacino colírio", l:["1 gota 4/4h (conjuntivite bacteriana)"]},
  {n:"Moxifloxacino colírio", l:["1 gota 8/8h"]},
  {n:"Cloranfenicol colírio", l:["1 gota 4/4h–6/6h"]},
  {n:"Olopatadina colírio", k:["Patanol"], l:["1 gota 12/12h (0,1%) ou 1x/dia (0,2%)"]},
  {n:"Cetotifeno colírio", l:["1 gota 12/12h"]},
  {n:"Lágrima artificial", k:["Carboximetilcelulose colírio","Lubrificante ocular"], l:["1 gota 4–6x/dia se necessário"]},
  {n:"Dexametasona colírio", l:["1 gota 4/4h–6/6h (uso curto, com cautela)"]},
  {n:"Prednisolona colírio", l:["1 gota 6/6h (acetato 1%)"]},
  {n:"Timolol colírio", l:["1 gota 12/12h (glaucoma)"]},
  {n:"Latanoprosta colírio", k:["Xalatan"], l:["1 gota à noite (glaucoma)"]},
  {n:"Brimonidina colírio", l:["1 gota 12/12h"]},
  {n:"Dorzolamida colírio", l:["1 gota 8/8h"]},
  /* ══ Lote 4: PSIQUIATRIA / NEURO (classe completa) ══ */
  /* Antidepressivos — completar (ISRS, IRSN, atípicos, tricíclicos, IMAO) */
  {n:"Fluvoxamina", l:["50–100 mg VO à noite (até 300 mg/dia)"]},
  {n:"Desvenlafaxina", k:["Pristiq"], l:["50 mg VO 1x/dia"]},
  {n:"Vortioxetina", k:["Brintellix"], l:["10 mg VO 1x/dia (faixa 5–20 mg/dia)"]},
  {n:"Agomelatina", k:["Valdoxan"], l:["25 mg VO à noite (até 50 mg)"]},
  {n:"Imipramina", l:["25 mg VO 1–3x/dia, titular (75–150 mg/dia)"]},
  {n:"Clomipramina", l:["25 mg VO/dia, titular (até 150–250 mg/dia)"]},
  {n:"Moclobemida", l:["150–300 mg VO 12/12h"]},
  {n:"Tianeptina", l:["12,5 mg VO 8/8h"]},
  /* Antipsicóticos */
  {n:"Risperidona", k:["Risperdal"], l:["1–6 mg VO/dia (iniciar 1–2 mg)"]},
  {n:"Olanzapina", k:["Zyprexa"], l:["5–20 mg VO à noite"]},
  {n:"Aripiprazol", k:["Abilify"], l:["10–15 mg VO 1x/dia (até 30 mg)"]},
  {n:"Ziprasidona", l:["40–80 mg VO 12/12h com alimento"]},
  {n:"Paliperidona", l:["3–12 mg VO 1x/dia"]},
  {n:"Lurasidona", l:["40 mg VO 1x/dia com alimento (até 160 mg)"]},
  {n:"Haloperidol", l:["1–5 mg VO/IM, titular"]},
  {n:"Clorpromazina", l:["25–100 mg VO até 8/8h"]},
  {n:"Levomepromazina", l:["25–100 mg/dia VO"]},
  {n:"Sulpirida", l:["50–150 mg/dia VO"]},
  {n:"Clozapina", l:["iniciar 12,5 mg/dia, titular lento (monitorar hemograma — risco de agranulocitose)"]},
  /* Estabilizadores do humor / anticonvulsantes */
  {n:"Carbonato de lítio", k:["Lítio","Carbolitium"], l:["300 mg VO 8/8h–12/12h; ajustar pela litemia (alvo 0,6–1,2 mEq/L)"]},
  {n:"Divalproato de sódio", k:["Ácido valproico","Valproato","Depakote"], l:["500 mg VO 12/12h, titular (nível 50–100 mcg/mL)"]},
  {n:"Lamotrigina", k:["Lamictal"], l:["25 mg/dia por 2 sem, 50 mg por 2 sem, 100 mg na sem 5, 200 mg manutenção — titular devagar (risco de rash); metade da dose se em uso de valproato"]},
  {n:"Carbamazepina", k:["Tegretol"], l:["200 mg VO 12/12h, titular (400–1200 mg/dia)"]},
  {n:"Oxcarbazepina", k:["Trileptal"], l:["300 mg VO 12/12h, titular"]},
  {n:"Topiramato", l:["25 mg VO à noite, titular (profilaxia de enxaqueca 50–100 mg/dia)"]},
  /* Benzodiazepínicos / hipnóticos (controlados) */
  {n:"Lorazepam", l:["1–2 mg VO (controlado)"]},
  {n:"Bromazepam", l:["3–6 mg VO/dia (controlado)"]},
  {n:"Clobazam", l:["10–20 mg VO/dia (controlado)"]},
  {n:"Midazolam", l:["7,5–15 mg VO à noite (controlado)"]},
  {n:"Zopiclona", l:["7,5 mg VO à noite (controlado)"]},
  {n:"Eszopiclona", l:["2–3 mg VO à noite (controlado)"]},
  /* Demência / cognição */
  {n:"Donepezila", l:["5 mg VO à noite por 4–6 sem, depois 10 mg"]},
  {n:"Rivastigmina", l:["1,5 mg VO 12/12h, titular; adesivo 4,6 → 9,5 mg/dia"]},
  {n:"Galantamina", l:["8 mg VO/dia, titular até 16–24 mg"]},
  {n:"Memantina", l:["5 mg VO/dia, titular semanal até 10 mg 12/12h"]},
  /* Estimulantes / TDAH (controlados) */
  {n:"Metilfenidato", k:["Ritalina","Concerta"], l:["10 mg VO 2–3x/dia (liberação imediata); LA/OROS 1x/dia pela manhã (controlado)"]},
  {n:"Lisdexanfetamina", k:["Venvanse"], l:["30 mg VO 1x/dia pela manhã (controlado)"]},
  /* ══ Lote 5: COMPLETAR CARDIOVASCULAR + ENDÓCRINO/METABÓLICO ══ */
  /* BRA (adicionais) */
  {n:"Telmisartana", k:["Micardis"], l:["40–80 mg VO 1x/dia"]},
  {n:"Olmesartana", k:["Benicar"], l:["20–40 mg VO 1x/dia"]},
  {n:"Candesartana", l:["8–32 mg VO 1x/dia"]},
  {n:"Irbesartana", l:["150–300 mg VO 1x/dia"]},
  /* IECA (adicionais) */
  {n:"Lisinopril", l:["10–40 mg VO 1x/dia"]},
  {n:"Perindopril", l:["4–8 mg VO 1x/dia"]},
  {n:"Benazepril", l:["10–40 mg VO 1x/dia"]},
  /* Bloqueadores de canal de cálcio (adicionais) */
  {n:"Diltiazem", l:["180–360 mg/dia VO (liberação prolongada 1x/dia)"]},
  {n:"Verapamil", l:["80 mg VO 8/8h ou 240 mg LP 1x/dia"]},
  {n:"Lercanidipino", l:["10–20 mg VO 1x/dia"]},
  {n:"Manidipino", l:["10–20 mg VO 1x/dia"]},
  {n:"Nitrendipino", l:["20 mg VO 1x/dia"]},
  /* Betabloqueadores (adicionais) */
  {n:"Nebivolol", l:["5 mg VO 1x/dia (até 10 mg)"]},
  {n:"Nadolol", l:["40–80 mg VO 1x/dia"]},
  /* Diuréticos (adicionais) */
  {n:"Amilorida", l:["5–10 mg VO 1x/dia"]},
  {n:"Torasemida", l:["5–20 mg VO 1x/dia"]},
  {n:"Bumetanida", l:["0,5–2 mg VO 1x/dia"]},
  /* Ação central / alfabloqueadores */
  {n:"Metildopa", l:["250–500 mg VO 8/8h–12/12h (HAS na gestação)"]},
  {n:"Clonidina", l:["0,1–0,2 mg VO 12/12h"]},
  {n:"Doxazosina", l:["1–8 mg VO 1x/dia"]},
  {n:"Prazosina", l:["1–5 mg VO 8/8h–12/12h"]},
  /* Antianginosos / insuficiência cardíaca */
  {n:"Mononitrato de isossorbida", k:["Isossorbida","Monocordil"], l:["20–40 mg VO 12/12h"]},
  {n:"Trimetazidina", l:["35 mg VO 12/12h"]},
  {n:"Ivabradina", k:["Procoralan"], l:["5 mg VO 12/12h (até 7,5 mg)"]},
  {n:"Digoxina", k:["Lanoxin"], l:["0,125–0,25 mg VO 1x/dia"]},
  {n:"Sacubitril + valsartana", k:["Sacubitril valsartana","Entresto"], l:["iniciar 49/51 mg VO 12/12h (24/26 mg se naïve/dose baixa), titular a cada 2–4 sem até 97/103 mg 12/12h; washout 36h de IECA"]},
  /* Antiarrítmicos */
  {n:"Amiodarona", k:["Ancoron","Cordarone"], l:["ataque 200 mg VO 8/8h por 7–10 dias, depois 200 mg 1x/dia"]},
  {n:"Propafenona", l:["150 mg VO 8/8h"]},
  {n:"Sotalol", l:["80 mg VO 12/12h"]},
  /* Dislipidemia (adicionais) */
  {n:"Pravastatina", l:["20–40 mg VO à noite"]},
  {n:"Pitavastatina", l:["1–4 mg VO 1x/dia"]},
  {n:"Lovastatina", l:["20–40 mg VO à noite"]},
  {n:"Genfibrozila", l:["600 mg VO 12/12h"]},
  {n:"Ciprofibrato", l:["100 mg VO 1x/dia"]},
  {n:"Evolocumabe", k:["Repatha"], l:["140 mg SC a cada 2 semanas (ou 420 mg 1x/mês)"]},
  /* Antidiabéticos (adicionais) */
  {n:"Glimepirida", k:["Amaryl"], l:["1–4 mg VO 1x/dia"]},
  {n:"Pioglitazona", k:["Actos"], l:["15–45 mg VO 1x/dia"]},
  {n:"Acarbose", k:["Glucobay"], l:["50–100 mg VO 8/8h no início das refeições"]},
  {n:"Repaglinida", l:["0,5–4 mg VO antes das refeições"]},
  {n:"Linagliptina", k:["Trajenta"], l:["5 mg VO 1x/dia"]},
  {n:"Vildagliptina", k:["Galvus"], l:["50 mg VO 12/12h"]},
  {n:"Saxagliptina", l:["5 mg VO 1x/dia"]},
  {n:"Canagliflozina", k:["Invokana"], l:["100–300 mg VO 1x/dia"]},
  {n:"Tirzepatida", k:["Mounjaro"], l:["2,5 mg SC 1x/semana por 4 sem, depois 5 mg; aumentar 2,5 mg a cada 4 sem (máx 15 mg)"]},
  {n:"Insulina regular", l:["individualizada, 30 min antes das refeições (SC)"]},
  {n:"Insulina lispro", l:["individualizada, imediatamente antes das refeições"]},
  {n:"Insulina asparte", l:["individualizada, imediatamente antes das refeições"]},
  {n:"Insulina glulisina", l:["individualizada, imediatamente antes das refeições"]},
  {n:"Insulina detemir", l:["individualizada 1–2x/dia"]},
  {n:"Insulina degludeca", l:["individualizada 1x/dia (ação ultralonga)"]},
  /* Tireoide (antitireoidianos) */
  {n:"Metimazol", k:["Tiamazol","Tapazol"], l:["10–30 mg VO/dia (manutenção 5–10 mg)"]},
  {n:"Propiltiouracil", l:["100 mg VO 8/8h (preferir no 1º trimestre de gestação)"]},
  /* Corticoides (adicionais) */
  {n:"Metilprednisolona", l:["VO conforme indicação; pulso IV 500–1000 mg/dia por 3 dias"]},
  {n:"Deflazacorte", l:["6–90 mg VO/dia conforme indicação"]},
  /* ══ Lote 6: RESPIRATÓRIO + ANALGESIA/AINE/OPIOIDES/ENXAQUECA + GASTRO ══ */
  /* Respiratório — inalatórios / nasais */
  {n:"Beclometasona inalatória", k:["Beclometasona","Clenil"], l:["250–500 mcg inalados 12/12h"]},
  {n:"Fluticasona inalatória", k:["Fluticasona"], l:["125–250 mcg inalados 12/12h"]},
  {n:"Ciclesonida", l:["160 mcg inalados 1x/dia"]},
  {n:"Salmeterol + fluticasona", k:["Salmeterol fluticasona","Seretide"], l:["1 inalação 12/12h"]},
  {n:"Brometo de ipratrópio", k:["Ipratrópio","Atrovent"], l:["2 jatos (40 mcg) inalados 6/6h"]},
  {n:"Tiotrópio", k:["Spiriva"], l:["1 inalação (18 mcg) 1x/dia (DPOC)"]},
  {n:"Umeclidínio + vilanterol", l:["1 inalação 1x/dia (DPOC)"]},
  {n:"Fenoterol", k:["Berotec"], l:["inalar/nebulizar na crise, se necessário"]},
  {n:"Montelucaste", k:["Singulair"], l:["10 mg VO à noite"]},
  {n:"Teofilina", l:["200–300 mg VO 12/12h"]},
  {n:"Budesonida nasal", l:["1–2 jatos por narina 1x/dia (rinite)"]},
  {n:"Mometasona nasal", l:["2 jatos por narina 1x/dia (rinite)"]},
  {n:"Fluticasona nasal", l:["2 jatos por narina 1x/dia (rinite)"]},
  {n:"Azelastina nasal", l:["1 jato por narina 12/12h"]},
  {n:"Oximetazolina nasal", l:["1 jato por narina 12/12h (máx 3–5 dias)"]},
  /* Analgesia / AINEs (adicionais) */
  {n:"Etoricoxibe", k:["Arcoxia"], l:["60–90 mg VO 1x/dia"]},
  {n:"Meloxicam", l:["7,5–15 mg VO 1x/dia"]},
  {n:"Piroxicam", l:["20 mg VO 1x/dia"]},
  {n:"Tenoxicam", l:["20 mg VO 1x/dia"]},
  {n:"Cetorolaco", k:["Toragesic"], l:["10 mg VO 6/6h (curto prazo, máx 5 dias)"]},
  {n:"Aceclofenaco", l:["100 mg VO 12/12h"]},
  {n:"Ácido mefenâmico", l:["500 mg VO 8/8h"]},
  /* Opioides (controlados) */
  {n:"Morfina", k:["Dimorf"], l:["10 mg VO/SC 4/4h, titular (controlado)"]},
  {n:"Oxicodona", l:["10 mg VO 12/12h (liberação controlada; controlado)"]},
  {n:"Fentanil transdérmico", k:["Fentanil","Durogesic"], l:["adesivo 12–25 mcg/h a cada 72h (controlado)"]},
  {n:"Tapentadol", l:["50 mg VO 12/12h (controlado)"]},
  {n:"Metadona", l:["iniciar 2,5–5 mg VO 8/8h (por especialista; controlado)"]},
  {n:"Buprenorfina transdérmica", k:["Buprenorfina"], l:["adesivo 5–10 mcg/h por 7 dias (controlado)"]},
  /* Enxaqueca (crise + profilaxia) */
  {n:"Sumatriptano", k:["Imigran"], l:["50–100 mg VO na crise (máx 200 mg/dia)"]},
  {n:"Zolmitriptano", l:["2,5 mg VO na crise (até 5 mg)"]},
  {n:"Rizatriptano", l:["10 mg VO na crise"]},
  {n:"Naratriptano", l:["2,5 mg VO na crise"]},
  {n:"Flunarizina", l:["10 mg VO à noite (profilaxia)"]},
  {n:"Ergotamina + cafeína", k:["Ergotamina cafeína","Cefalium"], l:["1–2 comp na crise (máx 6/semana)"]},
  /* Gastro (adicionais) */
  {n:"Rabeprazol", k:["Pariet"], l:["20 mg VO 1x/dia"]},
  {n:"Dexlansoprazol", l:["30–60 mg VO 1x/dia"]},
  {n:"Itoprida", l:["50 mg VO 8/8h (procinético)"]},
  {n:"Sulfassalazina", l:["500 mg – 1 g VO 6/6h (DII/artrite)"]},
  {n:"Picossulfato de sódio", k:["Picossulfato"], l:["10–15 gotas VO à noite"]},
  {n:"Brometo de pinavério", k:["Pinavério"], l:["50–100 mg VO 8/8h"]},
  {n:"Mebeverina", l:["135 mg VO 8/8h"]},
  {n:"Prucaloprida", l:["2 mg VO 1x/dia (constipação crônica)"]},
  {n:"Ciproeptadina", l:["4 mg VO 8/8h"]},
  /* ══ Lote 7: ÓSSEO/GOTA + REUMATO/IMUNO + VITAMINAS/MINERAIS + URO/GINECO ══ */
  /* Ósseo / metabólico */
  {n:"Alendronato", k:["Fosamax"], l:["70 mg VO 1x/semana em jejum, em pé; não deitar por 30 min"]},
  {n:"Risedronato", l:["35 mg VO 1x/semana (jejum)"]},
  {n:"Ibandronato", l:["150 mg VO 1x/mês"]},
  {n:"Ácido zoledrônico", k:["Aclasta"], l:["5 mg IV 1x/ano (osteoporose)"]},
  {n:"Denosumabe", k:["Prolia"], l:["60 mg SC a cada 6 meses"]},
  {n:"Raloxifeno", l:["60 mg VO 1x/dia"]},
  {n:"Teriparatida", l:["20 mcg SC 1x/dia (osteoporose grave; por especialista)"]},
  {n:"Colecalciferol", k:["Vitamina D","Vitamina D3"], l:["1000–2000 UI/dia (manutenção)","50.000 UI/semana por 6–8 sem (reposição)"]},
  {n:"Carbonato de cálcio", k:["Cálcio","Cálcio + vitamina D"], l:["500–1000 mg de cálcio elementar/dia com as refeições"]},
  /* Gota / hiperuricemia */
  {n:"Colchicina", l:["0,5 mg VO 1–2x/dia (crise/profilaxia)"]},
  {n:"Alopurinol", k:["Zyloric"], l:["100–300 mg VO 1x/dia (iniciar 100 mg, titular)"]},
  {n:"Febuxostate", l:["40–80 mg VO 1x/dia"]},
  /* Reumato / imunossupressores */
  {n:"Metotrexato", l:["7,5–25 mg VO/SC 1x/SEMANA (+ ácido fólico) — dose reumato; NUNCA diário"]},
  {n:"Leflunomida", l:["20 mg VO 1x/dia"]},
  {n:"Hidroxicloroquina", k:["Plaquinol"], l:["≤5 mg/kg/dia VO (usual 400 mg/dia) — LES/AR"]},
  {n:"Azatioprina", l:["2–3 mg/kg/dia VO"]},
  {n:"Micofenolato de mofetila", k:["Micofenolato"], l:["1 g VO 12/12h"]},
  {n:"Ciclosporina", l:["2,5–5 mg/kg/dia VO divididos 12/12h (monitorar nível)"]},
  {n:"Tacrolimo", l:["0,05–0,1 mg/kg/dia VO 12/12h (monitorar nível)"]},
  {n:"Adalimumabe", k:["Humira"], l:["40 mg SC a cada 2 semanas"]},
  {n:"Etanercepte", l:["50 mg SC 1x/semana"]},
  /* Vitaminas / minerais */
  {n:"Vitamina B12", k:["Cianocobalamina"], l:["1000 mcg IM/dia por 1 sem, depois semanal/mensal (reposição)"]},
  {n:"Ácido fólico", l:["5 mg VO 1x/dia"]},
  {n:"Sulfato ferroso", l:["40–60 mg de ferro elementar VO 1–2x/dia (longe de laticínios)"]},
  {n:"Tiamina", k:["Vitamina B1"], l:["300 mg VO/IV/dia (etilismo/reposição)"]},
  {n:"Piridoxina", k:["Vitamina B6"], l:["25–50 mg VO/dia (profilaxia de neuropatia por isoniazida)"]},
  {n:"Cloreto de potássio", k:["Potássio"], l:["reposição conforme dosagem (ex.: 40–80 mEq/dia VO)"]},
  /* Uro / gineco / hormonal */
  {n:"Tansulosina", k:["Secotex"], l:["0,4 mg VO 1x/dia após refeição (HPB)"]},
  {n:"Alfuzosina", l:["10 mg VO 1x/dia"]},
  {n:"Finasterida", l:["5 mg VO 1x/dia (HPB)","1 mg VO 1x/dia (alopecia)"]},
  {n:"Dutasterida", k:["Avodart"], l:["0,5 mg VO 1x/dia"]},
  {n:"Oxibutinina", l:["5 mg VO 8/8h–12/12h (bexiga hiperativa)"]},
  {n:"Solifenacina", l:["5–10 mg VO 1x/dia"]},
  {n:"Tolterodina", l:["2 mg VO 12/12h"]},
  {n:"Mirabegrona", l:["50 mg VO 1x/dia"]},
  {n:"Sildenafila", k:["Viagra"], l:["50 mg VO ~1h antes (DE; máx 100 mg/dia)"]},
  {n:"Tadalafila", k:["Cialis"], l:["10–20 mg VO se necessário","5 mg VO 1x/dia (uso contínuo)"]},
  {n:"Ácido tranexâmico", k:["Transamin"], l:["250–500 mg VO/IV 8/8h (sangramento)"]},
  {n:"Etinilestradiol + levonorgestrel", k:["Anticoncepcional oral"], l:["1 comp/dia por 21 dias, pausa de 7 dias"]},
  {n:"Desogestrel", l:["1 comp/dia (uso contínuo)"]},
  {n:"Estradiol", l:["1 comp/dia (reposição hormonal; individualizar)"]},
  {n:"Miconazol creme vaginal", l:["1 aplicação à noite por 7 dias"]},
  {n:"Clotrimazol vaginal", l:["1 comprimido vaginal à noite por 3–7 dias"]},
  {n:"Metronidazol vaginal", l:["1 aplicação à noite por 5 dias"]},
  /* ══ Lote 8: ASSOCIAÇÕES / COFORMULADOS (uso comum no Brasil) ══ */
  /* Anti-hipertensivos */
  {n:"Losartana + hidroclorotiazida", k:["Losartana HCTZ","Aradois H","Hidrazida"], l:["1 comp VO 1x/dia (ex.: 50/12,5 mg)"]},
  {n:"Valsartana + hidroclorotiazida", k:["Diovan HCT"], l:["1 comp VO 1x/dia (ex.: 160/12,5 mg)"]},
  {n:"Olmesartana + hidroclorotiazida", k:["Benicar HCT"], l:["1 comp VO 1x/dia"]},
  {n:"Telmisartana + hidroclorotiazida", k:["Micardis HCT"], l:["1 comp VO 1x/dia"]},
  {n:"Enalapril + hidroclorotiazida", k:["Co-Renitec"], l:["1 comp VO 1x/dia"]},
  {n:"Anlodipino + valsartana", k:["Exforge"], l:["1 comp VO 1x/dia"]},
  {n:"Anlodipino + olmesartana", k:["Sevikar"], l:["1 comp VO 1x/dia"]},
  {n:"Olmesartana + anlodipino + hidroclorotiazida", k:["Sevikar HCT"], l:["1 comp VO 1x/dia (associação tripla)"]},
  {n:"Perindopril + indapamida", k:["Coversyl Plus"], l:["1 comp VO 1x/dia"]},
  {n:"Perindopril + anlodipino", k:["Coveram"], l:["1 comp VO 1x/dia"]},
  {n:"Ramipril + hidroclorotiazida", l:["1 comp VO 1x/dia"]},
  /* Diabetes */
  {n:"Metformina + vildagliptina", k:["Galvus Met"], l:["1 comp VO 12/12h"]},
  {n:"Metformina + sitagliptina", k:["Janumet"], l:["1 comp VO 12/12h"]},
  {n:"Metformina + linagliptina", k:["Trajenta Duo"], l:["1 comp VO 12/12h"]},
  {n:"Metformina + dapagliflozina", k:["Xigduo"], l:["1 comp VO 1x/dia (ou 12/12h)"]},
  {n:"Empagliflozina + linagliptina", k:["Glyxambi"], l:["1 comp VO 1x/dia pela manhã"]},
  {n:"Metformina + glibenclamida", k:["Glucovance"], l:["1 comp VO 12/12h com as refeições"]},
  /* Dislipidemia */
  {n:"Ezetimiba + sinvastatina", k:["Vytorin","Zetsim"], l:["1 comp VO à noite"]},
  {n:"Ezetimiba + rosuvastatina", l:["1 comp VO 1x/dia"]},
  {n:"Ezetimiba + atorvastatina", l:["1 comp VO 1x/dia"]},
  /* Respiratório */
  {n:"Formoterol + beclometasona", k:["Fostair"], l:["1–2 inalações 12/12h"]},
  {n:"Fluticasona + vilanterol", k:["Relvar"], l:["1 inalação 1x/dia"]},
  {n:"Tiotrópio + olodaterol", k:["Spiolto"], l:["2 inalações 1x/dia (DPOC)"]},
  {n:"Ipratrópio + fenoterol", k:["Duovent"], l:["nebulizar/2 jatos se necessário"]},
  {n:"Ipratrópio + salbutamol", k:["Combivent"], l:["2 jatos 6/6h"]},
  /* Analgésicos / sintomáticos */
  {n:"Paracetamol + codeína", k:["Tylex","Paco"], l:["1 comp VO 6/6h (controlado)"]},
  {n:"Tramadol + paracetamol", k:["Ultracet"], l:["1 comp VO 6/6h (controlado)"]},
  {n:"Paracetamol + cafeína + orfenadrina", k:["Dorflex"], l:["1 comp VO 8/8h"]},
  {n:"Paracetamol + carisoprodol + cafeína + diclofenaco", k:["Tandrilax","Torsilax"], l:["1 comp VO 8/8h por até 3 dias"]},
  {n:"Dipirona + escopolamina", k:["Buscopan composto","Buscofem"], l:["1 comp ou 40 gotas VO 6/6h–8/8h"]},
  {n:"Paracetamol + fenilefrina", k:["Resfenol","Naldecon"], l:["1 comp VO 6/6h (sintomático de gripe)"]},
  /* Dermatológicos */
  {n:"Betametasona + clotrimazol + gentamicina", k:["Quadriderm","Trok-N"], l:["aplicar 2x/dia na área afetada"]},
  {n:"Betametasona + gentamicina", l:["aplicar 2x/dia"]},
  {n:"Betametasona + ácido salicílico", k:["Diprosalic"], l:["aplicar 1–2x/dia"]},
  {n:"Nistatina + óxido de zinco", k:["Nistatina óxido de zinco"], l:["aplicar nas trocas de fralda (dermatite)"]},
  {n:"Neomicina + bacitracina", k:["Nebacetin"], l:["aplicar 2–3x/dia"]},
  /* Oftálmicos */
  {n:"Tobramicina + dexametasona colírio", k:["Tobradex"], l:["1 gota 4/4h–6/6h"]},
  {n:"Ciprofloxacino + dexametasona colírio", l:["1 gota 6/6h"]},
  {n:"Moxifloxacino + dexametasona colírio", l:["1 gota 8/8h"]},
  /* Ginecológicos / hormonais */
  {n:"Etinilestradiol + drospirenona", k:["Yaz","Yasmin"], l:["1 comp/dia"]},
  {n:"Etinilestradiol + gestodeno", l:["1 comp/dia"]},
  {n:"Etinilestradiol + ciproterona", k:["Diane 35","Diane"], l:["1 comp/dia"]},
  {n:"Estradiol + noretisterona", l:["1 comp/dia (reposição hormonal)"]},
  /* ══ Sintomáticos: antialérgicos + descongestionante / antitussígenos-expectorantes ══ */
  {n:"Loratadina + pseudoefedrina", k:["Claritin-D"], l:["1 comp VO 12/12h (sintomático de gripe/rinite)"]},
  {n:"Desloratadina + pseudoefedrina", l:["1 comp VO 12/12h"]},
  {n:"Fexofenadina + pseudoefedrina", k:["Allegra-D"], l:["1 comp VO 12/12h"]},
  {n:"Cetirizina + pseudoefedrina", l:["1 comp VO 12/12h"]},
  {n:"Dextrometorfano", l:["10–20 mg VO 4/4h–6/6h (antitússico)"]},
  {n:"Guaifenesina", l:["200–400 mg VO 4/4h (expectorante)"]},
  {n:"Levodropropizina", l:["60 mg VO 8/8h (antitússico)"]},
  {n:"Dextrometorfano + guaifenesina", l:["conforme apresentação, 6/6h (antitússico + expectorante)"]}
];
